### ISSUE TITLE
Forthcoming dependency need

### ISSUE THREAD

**Issue by mohawk2** [KJ7LNW/perl-PDL-Opt-Simplex-Simple#5]
Currently this module just depends on PDL. The next version of PDL will have a lot less in it, and PDL::Opt::Simplex is now a separate CPAN distro.

Therefore, you will need to add a dependency in your Makefile.PL to "PDL::Opt::Simplex". This came to light because of the downstream CI after P:O:Simplex was removed. Please add that and release the module, so I can leave this distro as a downstream without failures.

**Comment by KJ7LNW** [comment]
awesome thank you for the note!

**Comment by KJ7LNW** [comment]
Is PDL::Opt::Simplex already a separate distribution so I can release it now? If not then let me know when it comes out, and I will push a release.

**Comment by mohawk2** [comment]
It is already out. MetaCPAN is quite good and it would have been possible to check that without asking me ;-) But all you need to do is express the dependency, and the CPAN software will do the rest.

**Comment by KJ7LNW** [comment]
> It is already out. MetaCPAN is quite good and it would have been possible to check that without asking me ;-)

That is true, why did I not think of that! 

Released.
